---
- name: Deploy bot
  hosts: bot
  become: true
  vars:
    deploy_method: github
    repo_url: "https://github.com/YOUR_USER/tg-multiproject.git"
    bot_user: bot
    bot_home: /home/bot
    bot_bin: /home/bot/bin/tg-multiproject
    bot_src: /home/bot/src/tg-multiproject
  roles:
    - bot
